services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network
  
  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck:
        test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
        - app-network
    
  kafka-init:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Creating topics...' &&
        kafka-topics --bootstrap-server kafka:29092 --create --topic booking.create --partitions 1 --replication-factor 1 --if-not-exists &&
        kafka-topics --bootstrap-server kafka:29092 --create --topic booking.confirmation --partitions 1 --replication-factor 1 --if-not-exists &&
        kafka-topics --bootstrap-server kafka:29092 --create --topic booking.reject --partitions 1 --replication-factor 1 --if-not-exists &&   
        kafka-topics --bootstrap-server kafka:29092 --create --topic booking.cancelled --partitions 1 --replication-factor 1 --if-not-exists &&         
      
        echo 'Topics created successfully!' &&
        kafka-topics --bootstrap-server kafka:29092 --list
      "
    networks:
      - app-network

  postgres-event:
    image: postgres:16
    container_name: postgres-event
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${EVENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${EVENT_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - event_service_pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  postgres-booking:
    image: postgres:16
    container_name: postgres-booking
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${BOOKING_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BOOKING_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - booking_service_pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  postgres-authorization:
    image: postgres:16
    container_name: postgres-authorization
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTHORIZATION_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTHORIZATION_POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - authorization_service_pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5      
  
  event-service:
    build:
      context: ./Services
      dockerfile: Events/Dockerfile
    container_name: event-service
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      postgres-event:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy        
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__EventsConnection=${EVENT_DB_CONNECTION}
      - Kafka__BootstrapServers=kafka:29092
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiryMinutes=${JWT_EXPIRY_MINUTES}
      - Redis__ConnectionString=redis:6379,defaultDatabase=0,connectTimeout=1000,ssl=false
      - Redis__DefaultTTLMinutes=10
      - Otlp__Endpoint=http://jaeger:4317
    ports:
      - "5001:8080"
    networks:
      - app-network
    restart: unless-stopped    

  booking-service:
    build:
      context: ./Services
      dockerfile: Bookings/Dockerfile
    container_name: booking-service
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      postgres-booking:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__BookingsConnection=${BOOKING_DB_CONNECTION}
      - Kafka__BootstrapServers=kafka:29092
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiryMinutes=${JWT_EXPIRY_MINUTES}
      - Otlp__Endpoint=http://jaeger:4317
    ports:
      - "5002:8080"
    networks:
      - app-network
    restart: unless-stopped
  
  authorization-service:
    build:
      context: ./Services
      dockerfile: Authorization/Dockerfile
    container_name: authorization-service
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      postgres-authorization:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__AuthorizationConnection=${AUTHORIZATION_DB_CONNECTION}
      - Kafka__BootstrapServers=kafka:29092
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiryMinutes=${JWT_EXPIRY_MINUTES}
      - Otlp__Endpoint=http://jaeger:4317
    ports:
      - "5003:8080"
    networks:
      - app-network
    restart: unless-stopped
    
  redis:
    image: redis:7.2-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "6379:6379"
    networks:
      - app-network
      
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: eventapi-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: eventapi-jaeger
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - app-network
      
  grafana:
    image: grafana/grafana:10.4.2
    container_name: eventapi-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app-network
      
volumes:
  kafka_data:
  event_service_pgdata:
  booking_service_pgdata:
  authorization_service_pgdata:
  grafana-data:
    
networks:
  app-network:
    driver: bridge
